name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - name: Publish
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
